### PR TITLE
Update CRD name

### PR DESCRIPTION
**Pull request by DanielXLee**
Fixed https://github.com/IBM/common-service-operator/issues/3

### CODE REVIEW

**Comment by gyliu513** [comment]
@DanielXLee  you can use `Fixed #xxxx` for future PRs, this can close the issue after the PR got merged.

**Comment by gyliu513** [comment]
lgtm

Leave to @horis233 @chenzhiwei for merge.

**Comment by gyliu513** [comment]
@morvencao can you help check why this not merged？

**Comment by morvencao** [comment]
@gyliu513 need to update config file to reflect the repo name change.

**Comment by morvencao** [comment]
https://github.com/IBM/test-infra/pull/87 merged, please check if tide is working for future PRs.

**Pull request merged**
